### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by dimkadimon** [wikicite/wikicite-data#16]
I get a runtime error when running make on pubtypes:

```
make data/wikidata-20181217.pubtypes 
./js/subclasses.js Q732577 Q191067 < data/wikidata-20181217.classes.csv | sort > data/wikidata-20181217.pubtypes

.../wikicite-data-master/js/subclasses.js:12
    .on('data', (line) => {
                        ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

**Comment by nichtich** [comment]
Looks like you use an old version of NodeJS. At least version 6 is needed.
